using NetoDotNET;
using NUnit.Framework;
using System;
using System.Net.Http;

namespace Tests
{
    public class ProductGetItemTests
    {
        private string _productJSONExample;
       

        [SetUp]
        public void Setup()
        {
            _productJSONExample = @"{
	""Item"": [{
		""SupplierItemCode"": """",
		""Features"": """",
		""EditableKitBundle"": ""False"",
		""IsActive"": ""True"",
		""eBayDescription"": """",
		""Misc24"": """",
		""IsBought"": ""n"",
		""UPC3"": """",
		""ShippingHeight"": ""0.600"",
		""PromotionExpiryDateUTC"": ""2019-03-27 14:00:00"",
		""Misc03"": """",
		""SubType"": """",
		""ReferenceNumber"": ""0"",
		""Misc32"": """",
		""ProductURL"": """",
		""Misc16"": """",
		""ImageURL"": ""https://cdn.neto.com.au/assets/sample_data/products/main/1.jpg"",
		""Group"": ""0"",
		""Misc30"": """",
		""ShortDescription"": """",
		""TaxFreeItem"": ""False"",
		""SellUnitQuantity"": ""1"",
		""Brand"": """",
		""BaseUnitPerQuantity"": ""1.0000"",
		""PriceGroups"": [{
			""PriceGroup"": {
				""Multiple"": """",
				""Price"": ""79.95"",
				""MaximumQuantity"": """",
				""MinimumQuantity"": """",
				""Group"": ""A"",
				""GroupID"": ""1"",
				""PromotionPrice"": ""71.96"",
				""MultipleStartQuantity"": """"
			}
		}],
		""ItemSpecifics"": [{
			""ItemSpecific"": {
				""Value"": ""White"",
				""Name"": ""Colour""
			}
		}],
		""DateAdded"": ""0000-00-00 00:00:00"",
		""Subtitle"": ""Modern furniture for the modern home"",
		""TermsAndConditions"": """",
		""PickZone"": """",
		""Misc13"": """",
		""RestrictedToUserGroup"": ""0"",
		""BaseUnitOfMeasure"": """",
		""Misc41"": """",
		""ShippingLength"": ""0.600"",
		""Misc05"": """",
		""Misc49"": """",
		""Categories"": [{
			""Category"": {
				""CategoryID"": ""99"",
				""Priority"": ""0"",
				""CategoryName"": ""[Sample] Sub Category""
			}
		}],
		""NumbersOfLabelsToPrint"": ""1"",
		""WarehouseQuantity"": {
			""WarehouseID"": ""1"",
			""Quantity"": ""7""
		},
		""Misc38"": """",
		""AccountingCode"": """",
		""Misc42"": """",
		""AvailabilityDescription"": """",
		""DateAddedLocal"": ""0000-00-00 00:00:00"",
		""Misc21"": """",
		""SalesChannels"": {
			""SalesChannel"": [{
				""SalesChannelName"": ""Webstore"",
				""SalesChannelID"": ""1"",
				""IsApproved"": ""True""
			}, {
				""SalesChannelName"": ""Neto POS"",
				""SalesChannelID"": ""2"",
				""IsApproved"": ""False""
			}]
		},
		""SEOPageTitle"": """",
		""Misc35"": """",
		""DateUpdatedLocal"": ""2019-03-14 22:26:49"",
		""AutomaticURL"": ""False"",
		""UPC1"": ""123456789"",
		""ExpenseAccount"": """",
		""SortOrder2"": ""0"",
		""Misc37"": """",
		""SplitForWarehousePicking"": ""y"",
		""Misc02"": """",
		""AssetAccount"": """",
		""UnitOfMeasure"": """",
		""Job"": ""0"",
		""PickPriority"": ""FIFO"",
		""Misc52"": """",
		""Misc28"": """",
		""RequiresPackaging"": ""False"",
		""SerialTracking"": ""False"",
		""ItemLength"": ""0.000"",
		""CommittedQuantity"": ""6"",
		""Misc44"": """",
		""Virtual"": ""False"",
		""ID"": ""1"",
		""Misc17"": """",
		""Misc07"": """",
		""SortOrder1"": ""0"",
		""PromotionStartDateUTC"": ""2019-03-13 14:00:00"",
		""Misc11"": """",
		""SEOPageHeading"": """",
		""SEOMetaDescription"": ""My SEO description for Google."",
		""PromotionPrice"": ""71.96"",
		""PromotionExpiryDate"": ""2019-03-28 00:00:00"",
		""Misc25"": """",
		""Misc23"": """",
		""PromotionStartDateLocal"": ""2019-03-14 00:00:00"",
		""Misc50"": """",
		""SKU"": ""SMP_1"",
		""Misc29"": """",
		""BrochureURL"": """",
		""Misc22"": """",
		""Model"": ""[Sample] Americana Dining Chair"",
		""Misc43"": """",
		""SEOCanonicalURL"": """",
		""DateArrival"": ""0000-00-00"",
		""Misc04"": """",
		""ShippingWidth"": ""0.600"",
		""Misc48"": """",
		""SearchKeywords"": """",
		""Misc15"": """",
		""Misc09"": """",
		""WhenToRepeatOnStandingOrders"": """",
		""Images"": [{
			""URL"": ""https://netodotnet.neto.com.au/assets/full/SMP_1.jpg"",
			""Timestamp"": ""2019-03-14 12:26:49"",
			""ThumbURL"": ""https://netodotnet.neto.com.au/assets/thumb/SMP_1.jpg"",
			""MediumThumbURL"": ""https://netodotnet.neto.com.au/assets/thumbL/SMP_1.jpg"",
			""Name"": ""Main""
		}],
		""Misc39"": """",
		""CostOfSalesAccount"": """",
		""PrimarySupplier"": """",
		""Misc10"": """",
		""Misc34"": """",
		""Misc19"": """",
		""Misc33"": """",
		""WarehouseLocations"": [{
			""WarehouseLocation"": """"
		}],
		""ItemHeight"": ""0.000"",
		""Misc46"": """",
		""FreeGifts"": [""""],
		""Misc20"": """",
		""CostPrice"": ""0.00000000"",
		""Misc40"": """",
		""Warranty"": """",
		""PromotionStartDate"": ""2019-03-14 00:00:00"",
		""DateAddedUTC"": ""0000-00-00 00:00:00"",
		""Misc31"": """",
		""BarcodeHeight"": ""0"",
		""DefaultPrice"": ""79.95"",
		""BuyUnitQuantity"": ""1"",
		""Misc36"": """",
		""DateUpdated"": ""2019-03-14 22:26:49"",
		""Misc14"": """",
		""Name"": ""[Sample] Americana Dining Chair"",
		""Specifications"": """",
		""Misc01"": """",
		""DateUpdatedUTC"": ""2019-03-14 12:26:49"",
		""IsSold"": ""n"",
		""ModelNumber"": """",
		""QuantityPerScan"": ""1"",
		""UPC2"": """",
		""Misc45"": """",
		""Format"": """",
		""Approved"": ""True"",
		""IsAsset"": ""False"",
		""CrossSellProducts"": """",
		""Type"": """",
		""ItemURL"": ""sample-americana-dining-chair"",
		""DisplayTemplate"": """",
		""MonthlySpendRequirement"": ""0.00"",
		""ArtistOrAuthor"": """",
		""Misc51"": """",
		""IncomeAccount"": """",
		""Misc06"": """",
		""CubicWeight"": ""0.000000"",
		""Misc47"": """",
		""DateArrivalUTC"": ""0000-00-00"",
		""ShippingWeight"": ""0.8500"",
		""PromotionExpiryDateLocal"": ""2019-03-28 00:00:00"",
		""PurchaseTaxCode"": """",
		""Misc27"": """",
		""RelatedContents"": """",
		""InternalNotes"": """",
		""Misc18"": """",
		""SEOMetaKeywords"": """",
		""TaxInclusive"": ""True"",
		""RRP"": ""99.95"",
		""UpsellProducts"": [""""],
		""ParentSKU"": """",
		""ItemWidth"": ""0.000"",
		""Misc12"": """",
		""Misc26"": """",
		""Misc08"": """",
		""ShippingCategory"": ""0"",
		""IsInventoried"": ""n"",
		""InventoryID"": ""1"",
		""UPC"": """",
		""KitComponents"": [{
			""KitComponent"": """"
		}],
		""Description"": ""<p>Product descriptions and images are an important part of any product listing. In a recent survey, 63% of shoppers reported them as very important to their decision-making process.</p>\n\n<p><em>This is an example product description for a demonstration product. Purchases of this product will not be fulfilled. </em></p>\n\n<p>Product descriptions can contain text, images, YouTube videos, html and even javascript. Product descriptions should be less than 600 words in length and should highlight the features and benefits of the product you are selling.</p>\n\n<p>Unique product descriptions that are well written and content rich can help to improve your search engine rankings and sales conversion rates. Try to avoid copying and pasting product descriptions from competitor or manufacturer websites. This is deemed to be duplicate content and could negatively impact your search engine rankings.</p>\n\n<p>You should invest in high-quality product images because the perceived value of your products is directly impacted by the quality of your product images. To get started, invest in a good camera, tripod, light box and a few YouTube tutorials. Alternatively, you can always request high-quality photographs from the product's manufacturer.</p>\n\n<p><em>This demonstration product and its related sales data will automatically be deleted if you choose to subscribe to a paid plan.</em></p>\n\n<p>&nbsp;</p>\n""
	}, {
		""SupplierItemCode"": """",
		""Features"": """",
		""EditableKitBundle"": ""False"",
		""IsActive"": ""True"",
		""eBayDescription"": """",
		""Misc24"": """",
		""IsBought"": ""n"",
		""UPC3"": """",
		""ShippingHeight"": ""0.600"",
		""PromotionExpiryDateUTC"": ""2019-03-27 14:00:00"",
		""Misc03"": """",
		""SubType"": """",
		""ReferenceNumber"": ""0"",
		""Misc32"": """",
		""ProductURL"": """",
		""Misc16"": """",
		""ImageURL"": ""https://cdn.neto.com.au/assets/sample_data/products/main/10.jpg"",
		""Group"": ""0"",
		""Misc30"": """",
		""ShortDescription"": """",
		""TaxFreeItem"": ""False"",
		""SellUnitQuantity"": ""1"",
		""Brand"": """",
		""BaseUnitPerQuantity"": ""1.0000"",
		""PriceGroups"": [{
			""PriceGroup"": {
				""Multiple"": """",
				""Price"": ""149.95"",
				""MaximumQuantity"": """",
				""MinimumQuantity"": """",
				""MultipleStartQuantity"": """",
				""Group"": ""A"",
				""GroupID"": ""1""
			}
		}],
		""ItemSpecifics"": [{
			""ItemSpecific"": """"
		}],
		""DateAdded"": ""0000-00-00 00:00:00"",
		""Subtitle"": ""Modern furniture for the modern home"",
		""TermsAndConditions"": """",
		""PickZone"": """",
		""Misc13"": """",
		""RestrictedToUserGroup"": ""0"",
		""BaseUnitOfMeasure"": """",
		""Misc41"": """",
		""ShippingLength"": ""0.600"",
		""Misc05"": """",
		""Misc49"": """",
		""Categories"": [{
			""Category"": {
				""CategoryID"": ""99"",
				""Priority"": ""0"",
				""CategoryName"": ""[Sample] Sub Category""
			}
		}],
		""NumbersOfLabelsToPrint"": ""1"",
		""WarehouseQuantity"": """",
		""Misc38"": """",
		""AccountingCode"": """",
		""Misc42"": """",
		""AvailabilityDescription"": """",
		""DateAddedLocal"": ""0000-00-00 00:00:00"",
		""Misc21"": """",
		""SalesChannels"": {
			""SalesChannel"": [{
				""SalesChannelName"": ""Webstore"",
				""SalesChannelID"": ""1"",
				""IsApproved"": ""True""
			}, {
				""SalesChannelName"": ""Neto POS"",
				""SalesChannelID"": ""2"",
				""IsApproved"": ""False""
			}]
		},
		""SEOPageTitle"": """",
		""Misc35"": """",
		""DateUpdatedLocal"": ""2019-03-14 22:27:03"",
		""AutomaticURL"": ""False"",
		""UPC1"": ""123456798"",
		""ExpenseAccount"": """",
		""SortOrder2"": ""0"",
		""Misc37"": """",
		""SplitForWarehousePicking"": ""y"",
		""Misc02"": """",
		""AssetAccount"": """",
		""UnitOfMeasure"": """",
		""Job"": ""0"",
		""PickPriority"": ""FIFO"",
		""Misc52"": """",
		""Misc28"": """",
		""RequiresPackaging"": ""False"",
		""SerialTracking"": ""False"",
		""ItemLength"": ""0.000"",
		""CommittedQuantity"": ""0"",
		""Misc44"": """",
		""Virtual"": ""False"",
		""ID"": ""2"",
		""Misc17"": """",
		""Misc07"": """",
		""SortOrder1"": ""0"",
		""PromotionStartDateUTC"": ""2019-03-13 14:00:00"",
		""Misc11"": """",
		""SEOPageHeading"": """",
		""SEOMetaDescription"": ""My SEO description for Google."",
		""PromotionExpiryDate"": ""2019-03-28 00:00:00"",
		""Misc25"": """",
		""Misc23"": """",
		""PromotionStartDateLocal"": ""2019-03-14 00:00:00"",
		""Misc50"": """",
		""SKU"": ""SMP_10"",
		""Misc29"": """",
		""BrochureURL"": """",
		""Misc22"": """",
		""Model"": ""[Sample] Bently Luxury Dining Chair"",
		""Misc43"": """",
		""SEOCanonicalURL"": """",
		""DateArrival"": ""0000-00-00"",
		""Misc04"": """",
		""ShippingWidth"": ""0.600"",
		""Misc48"": """",
		""SearchKeywords"": """",
		""Misc15"": """",
		""Misc09"": """",
		""WhenToRepeatOnStandingOrders"": """",
		""Images"": [{
			""URL"": ""https://netodotnet.neto.com.au/assets/full/SMP_10.jpg"",
			""Timestamp"": ""2019-03-14 12:26:41"",
			""ThumbURL"": ""https://netodotnet.neto.com.au/assets/thumb/SMP_10.jpg"",
			""MediumThumbURL"": ""https://netodotnet.neto.com.au/assets/thumbL/SMP_10.jpg"",
			""Name"": ""Main""
		}, {
			""URL"": ""https://netodotnet.neto.com.au/assets/alt_1/SMP_10.jpg"",
			""Timestamp"": ""2019-03-14 12:26:58"",
			""ThumbURL"": ""https://netodotnet.neto.com.au/assets/alt_1_thumb/SMP_10.jpg"",
			""Name"": ""Alt 1""
		}, {
			""URL"": ""https://netodotnet.neto.com.au/assets/alt_2/SMP_10.jpg"",
			""Timestamp"": ""2019-03-14 12:27:02"",
			""ThumbURL"": ""https://netodotnet.neto.com.au/assets/alt_2_thumb/SMP_10.jpg"",
			""Name"": ""Alt 2""
		}],
		""Misc39"": """",
		""CostOfSalesAccount"": """",
		""PrimarySupplier"": """",
		""Misc10"": """",
		""Misc34"": """",
		""Misc19"": """",
		""Misc33"": """",
		""WarehouseLocations"": [{
			""WarehouseLocation"": """"
		}],
		""ItemHeight"": ""0.000"",
		""Misc46"": """",
		""FreeGifts"": [""""],
		""Misc20"": """",
		""CostPrice"": ""0.00000000"",
		""Misc40"": """",
		""Warranty"": """",
		""PromotionStartDate"": ""2019-03-14 00:00:00"",
		""DateAddedUTC"": ""0000-00-00 00:00:00"",
		""Misc31"": """",
		""BarcodeHeight"": ""0"",
		""DefaultPrice"": ""149.95"",
		""BuyUnitQuantity"": ""1"",
		""Misc36"": """",
		""DateUpdated"": ""2019-03-14 22:27:03"",
		""Misc14"": """",
		""Name"": ""[Sample] Bently Luxury Dining Chair"",
		""Specifications"": """",
		""Misc01"": """",
		""DateUpdatedUTC"": ""2019-03-14 12:27:03"",
		""IsSold"": ""n"",
		""ModelNumber"": """",
		""QuantityPerScan"": ""1"",
		""UPC2"": """",
		""Misc45"": """",
		""Format"": """",
		""Approved"": ""True"",
		""IsAsset"": ""False"",
		""CrossSellProducts"": """",
		""Type"": """",
		""ItemURL"": ""sample-bently-luxury-dining-chair"",
		""DisplayTemplate"": """",
		""MonthlySpendRequirement"": ""0.00"",
		""ArtistOrAuthor"": """",
		""Misc51"": """",
		""IncomeAccount"": """",
		""Misc06"": """",
		""CubicWeight"": ""0.000000"",
		""Misc47"": """",
		""DateArrivalUTC"": ""0000-00-00"",
		""ShippingWeight"": ""0.8500"",
		""PromotionExpiryDateLocal"": ""2019-03-28 00:00:00"",
		""PurchaseTaxCode"": """",
		""Misc27"": """",
		""RelatedContents"": """",
		""InternalNotes"": """",
		""Misc18"": """",
		""SEOMetaKeywords"": """",
		""TaxInclusive"": ""True"",
		""RRP"": ""199.95"",
		""UpsellProducts"": [""""],
		""ParentSKU"": """",
		""ItemWidth"": ""0.000"",
		""Misc12"": """",
		""Misc26"": """",
		""Misc08"": """",
		""ShippingCategory"": ""0"",
		""IsInventoried"": ""n"",
		""InventoryID"": ""2"",
		""UPC"": """",
		""KitComponents"": [{
			""KitComponent"": """"
		}],
		""Description"": ""<p>Product descriptions and images are an important part of any product listing. In a recent survey, 63% of shoppers reported them as very important to their decision-making process.</p>\n\n<p><em>This is an example product description for a demonstration product. Purchases of this product will not be fulfilled. </em></p>\n\n<p>Product descriptions can contain text, images, YouTube videos, html and even javascript. Product descriptions should be less than 600 words in length and should highlight the features and benefits of the product you are selling.</p>\n\n<p>Unique product descriptions that are well written and content rich can help to improve your search engine rankings and sales conversion rates. Try to avoid copying and pasting product descriptions from competitor or manufacturer websites. This is deemed to be duplicate content and could negatively impact your search engine rankings.</p>\n\n<p>You should invest in high-quality product images because the perceived value of your products is directly impacted by the quality of your product images. To get started, invest in a good camera, tripod, light box and a few YouTube tutorials. Alternatively, you can always request high-quality photographs from the product's manufacturer.</p>\n\n<p><em>This demonstration product and its related sales data will automatically be deleted if you choose to subscribe to a paid plan.</em></p>\n\n<p>&nbsp;</p>\n""
	}, {
		""SupplierItemCode"": """",
		""Features"": """",
		""EditableKitBundle"": ""False"",
		""IsActive"": ""True"",
		""eBayDescription"": """",
		""Misc24"": """",
		""IsBought"": ""n"",
		""UPC3"": """",
		""ShippingHeight"": ""0.600"",
		""PromotionExpiryDateUTC"": ""0000-00-00 00:00:00"",
		""Misc03"": """",
		""SubType"": """",
		""ReferenceNumber"": ""0"",
		""Misc32"": """",
		""ProductURL"": """",
		""Misc16"": """",
		""ImageURL"": ""https://cdn.neto.com.au/assets/sample_data/products/main/10_blue.jpg"",
		""Group"": ""0"",
		""Misc30"": """",
		""ShortDescription"": """",
		""TaxFreeItem"": ""False"",
		""SellUnitQuantity"": ""1"",
		""Brand"": """",
		""BaseUnitPerQuantity"": ""1.0000"",
		""PriceGroups"": [{
			""PriceGroup"": {
				""Multiple"": """",
				""Price"": ""149.95"",
				""MaximumQuantity"": """",
				""MinimumQuantity"": """",
				""MultipleStartQuantity"": """",
				""Group"": ""A"",
				""GroupID"": ""1""
			}
		}],
		""ItemSpecifics"": [{
			""ItemSpecific"": {
				""Value"": ""Blue"",
				""Name"": ""Colour""
			}
		}],
		""DateAdded"": ""0000-00-00 00:00:00"",
		""Subtitle"": """",
		""TermsAndConditions"": """",
		""PickZone"": """",
		""Misc13"": """",
		""RestrictedToUserGroup"": ""0"",
		""BaseUnitOfMeasure"": """",
		""Misc41"": """",
		""ShippingLength"": ""0.600"",
		""Misc05"": """",
		""Misc49"": """",
		""Categories"": [{
			""Category"": [{
				""CategoryID"": ""99"",
				""Priority"": ""0"",
				""CategoryName"": ""[Sample] Sub Category""
			}, {
				""CategoryID"": ""101"",
				""Priority"": ""0"",
				""CategoryName"": ""[Sample] Sub Category 2""
			}]
		}],
		""NumbersOfLabelsToPrint"": ""1"",
		""WarehouseQuantity"": """",
		""Misc38"": """",
		""AccountingCode"": """",
		""Misc42"": """",
		""AvailabilityDescription"": """",
		""DateAddedLocal"": ""0000-00-00 00:00:00"",
		""Misc21"": """",
		""SalesChannels"": {
			""SalesChannel"": [{
				""SalesChannelName"": ""Webstore"",
				""SalesChannelID"": ""1"",
				""IsApproved"": ""True""
			}, {
				""SalesChannelName"": ""Neto POS"",
				""SalesChannelID"": ""2"",
				""IsApproved"": ""False""
			}]
		},
		""SEOPageTitle"": ""[Sample] Bently Luxury Dining Chair [Colour: Blue]"",
		""Misc35"": """",
		""DateUpdatedLocal"": ""2019-03-14 22:29:30"",
		""AutomaticURL"": ""False"",
		""UPC1"": """",
		""ExpenseAccount"": """",
		""SortOrder2"": ""0"",
		""Misc37"": """",
		""SplitForWarehousePicking"": ""y"",
		""Misc02"": """",
		""AssetAccount"": """",
		""UnitOfMeasure"": """",
		""Job"": ""0"",
		""PickPriority"": ""FIFO"",
		""Misc52"": """",
		""Misc28"": """",
		""RequiresPackaging"": ""False"",
		""SerialTracking"": ""False"",
		""ItemLength"": ""0.000"",
		""CommittedQuantity"": ""0"",
		""Misc44"": """",
		""Virtual"": ""False"",
		""ID"": ""3"",
		""Misc17"": """",
		""Misc07"": """",
		""SortOrder1"": ""0"",
		""PromotionStartDateUTC"": ""0000-00-00 00:00:00"",
		""Misc11"": """",
		""SEOPageHeading"": """",
		""SEOMetaDescription"": """",
		""PromotionExpiryDate"": ""0000-00-00 00:00:00"",
		""Misc25"": """",
		""Misc23"": """",
		""PromotionStartDateLocal"": ""0000-00-00 00:00:00"",
		""Misc50"": """",
		""SKU"": ""SMP_10_blue"",
		""Misc29"": """",
		""BrochureURL"": """",
		""Misc22"": """",
		""Model"": ""[Sample] Bently Luxury Dining Chair [Colour: Blue]"",
		""Misc43"": """",
		""SEOCanonicalURL"": """",
		""DateArrival"": ""0000-00-00"",
		""Misc04"": """",
		""ShippingWidth"": ""0.600"",
		""Misc48"": """",
		""SearchKeywords"": """",
		""Misc15"": """",
		""Misc09"": """",
		""WhenToRepeatOnStandingOrders"": """",
		""Images"": [{
			""URL"": ""https://netodotnet.neto.com.au/assets/full/SMP_10_blue.jpg"",
			""Timestamp"": ""2019-03-14 12:26:42"",
			""ThumbURL"": ""https://netodotnet.neto.com.au/assets/thumb/SMP_10_blue.jpg"",
			""MediumThumbURL"": ""https://netodotnet.neto.com.au/assets/thumbL/SMP_10_blue.jpg"",
			""Name"": ""Main""
		}, {
			""URL"": ""https://netodotnet.neto.com.au/assets/alt_1/SMP_10.jpg"",
			""Timestamp"": ""2019-03-14 12:26:58"",
			""ThumbURL"": ""https://netodotnet.neto.com.au/assets/alt_1_thumb/SMP_10.jpg"",
			""Name"": ""Alt 1""
		}, {
			""URL"": ""https://netodotnet.neto.com.au/assets/alt_2/SMP_10.jpg"",
			""Timestamp"": ""2019-03-14 12:27:02"",
			""ThumbURL"": ""https://netodotnet.neto.com.au/assets/alt_2_thumb/SMP_10.jpg"",
			""Name"": ""Alt 2""
		}],
		""Misc39"": """",
		""CostOfSalesAccount"": """",
		""PrimarySupplier"": """",
		""Misc10"": """",
		""Misc34"": """",
		""Misc19"": """",
		""Misc33"": """",
		""WarehouseLocations"": [{
			""WarehouseLocation"": """"
		}],
		""ItemHeight"": ""0.000"",
		""Misc46"": """",
		""FreeGifts"": [""""],
		""Misc20"": """",
		""CostPrice"": ""0.00000000"",
		""Misc40"": """",
		""Warranty"": """",
		""PromotionStartDate"": ""0000-00-00 00:00:00"",
		""DateAddedUTC"": ""0000-00-00 00:00:00"",
		""Misc31"": """",
		""BarcodeHeight"": ""0"",
		""DefaultPrice"": ""149.95"",
		""BuyUnitQuantity"": ""1"",
		""Misc36"": """",
		""DateUpdated"": ""2019-03-14 22:29:30"",
		""Misc14"": """",
		""Name"": ""[Sample] Bently Luxury Dining Chair [Colour: Blue]"",
		""Specifications"": """",
		""Misc01"": """",
		""DateUpdatedUTC"": ""2019-03-14 12:29:30"",
		""IsSold"": ""n"",
		""ModelNumber"": """",
		""QuantityPerScan"": ""1"",
		""UPC2"": """",
		""Misc45"": """",
		""Format"": """",
		""Approved"": ""True"",
		""IsAsset"": ""False"",
		""CrossSellProducts"": """",
		""Type"": """",
		""ItemURL"": ""sample-bently-luxury-dining-chair-colour-blue"",
		""DisplayTemplate"": """",
		""MonthlySpendRequirement"": ""0.00"",
		""ArtistOrAuthor"": """",
		""Misc51"": """",
		""IncomeAccount"": """",
		""Misc06"": """",
		""CubicWeight"": ""0.000000"",
		""Misc47"": """",
		""DateArrivalUTC"": ""0000-00-00"",
		""ShippingWeight"": ""0.8500"",
		""PromotionExpiryDateLocal"": ""0000-00-00 00:00:00"",
		""PurchaseTaxCode"": """",
		""Misc27"": """",
		""RelatedContents"": """",
		""InternalNotes"": """",
		""Misc18"": """",
		""SEOMetaKeywords"": """",
		""TaxInclusive"": ""True"",
		""RRP"": ""0.00"",
		""UpsellProducts"": [""""],
		""ParentSKU"": ""SMP_10"",
		""ItemWidth"": ""0.000"",
		""Misc12"": """",
		""Misc26"": """",
		""Misc08"": """",
		""ShippingCategory"": ""0"",
		""IsInventoried"": ""n"",
		""InventoryID"": ""3"",
		""UPC"": """",
		""KitComponents"": [{
			""KitComponent"": """"
		}],
		""Description"": ""<p>Product descriptions and images are an important part of any product listing. In a recent survey, 63% of shoppers reported them as very important to their decision-making process.</p>\n\n<p><em>This is an example product description for a demonstration product. Purchases of this product will not be fulfilled. </em></p>\n\n<p>Product descriptions can contain text, images, YouTube videos, html and even javascript. Product descriptions should be less than 600 words in length and should highlight the features and benefits of the product you are selling.</p>\n\n<p>Unique product descriptions that are well written and content rich can help to improve your search engine rankings and sales conversion rates. Try to avoid copying and pasting product descriptions from competitor or manufacturer websites. This is deemed to be duplicate content and could negatively impact your search engine rankings.</p>\n\n<p>You should invest in high-quality product images because the perceived value of your products is directly impacted by the quality of your product images. To get started, invest in a good camera, tripod, light box and a few YouTube tutorials. Alternatively, you can always request high-quality photographs from the product's manufacturer.</p>\n\n<p><em>This demonstration product and its related sales data will automatically be deleted if you choose to subscribe to a paid plan.</em></p>\n\n<p>&nbsp;</p>\n""
	}],
	""CurrentTime"": ""2019-03-20 13:07:25"",
	""Ack"": ""Success""
}";
        }

        [Test]
        public void CanDeSerializeGetItemResponse()
        {

            var netoResponse = new NetoResponseBase();

            Assert.AreEqual("2019-03-20 13:07:25", netoResponse.CurrentTime);

        }
    }
}